on:
  workflow_dispatch:
    inputs:
      action:
        description: '操作'
        required: true
        default: '压测'
        type: choice
        options:
          - 远程
          - 压测
          - 配置项目

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name: '${{ inputs.action }}'

env:
  TZ: Asia/Shanghai

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_id: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v4
      - name: 设置环境变量
        run: |
          JOB_ID={{ matrix.job_id }}
          ACCOUNTS='[
            [],
            ["Shubhamchak2025@outlook.com", "35c0466E25EC83154D60", "G3U7NSDRIRMHTI25"],
            ["", "", ""],
            ["", "", ""]
          ]'
          USERNAME=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][0]")
          PASSWORD=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][1]")
          SECRET=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][2]")
          
          echo "GITHUB_USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "GITHUB_PASSWORD=$PASSWORD" >> $GITHUB_ENV
          echo "GITHUB_SECRET=$SECRET" >> $GITHUB_ENV

          yarn
          yarn build

      

      - name: 远程
        if: ${{ inputs.action == '远程' }}
        env:
          REMOTE: true
        run: | 
          node dist/app.js

      - name: 压测
        if: ${{ inputs.action == '压测' }}
        env:
          STRESS_TEST: true
        run: | 
          node dist/app.js

      - name: 配置项目
        if: ${{ inputs.action == '配置项目' }}
        env:
          RUN_CIRCLECI_SETUP: true
        run: | 
          node dist/app.js
